# Generated by Django 4.0.1 on 2022-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_amenities_alter_room_facilities_and_more'),
        ('lists', '0002_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='lists', to='rooms.Room'),
        ),
    ]
